article:
  type: tech # tech/story
  auto_excerpt: 200

logo:
  subtitle: 'Steven Wu | Back End Developer - Ruby' # '文字1 | 文字2' (鼠标放上去会切换到文字2)
  avatar: '[{config.avatar}](/about/)'
  title: '[{config.title}](/)'

comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    src: https://giscus.app/client.js
    data-repo: springwq/springwq.github.io # [在此输入仓库]
    data-repo-id:  MDEwOlJlcG9zaXRvcnkzNTcyMzg1MA== # [在此输入仓库 ID]
    data-category: Announcements # [在此输入分类名]
    data-category-id: DIC_kwDOAiEaSs4CgTq7
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous

footer:
   content: | # 支持 Markdown 格式
    stevenruby.com © 2024 | Powered by [Hexo](https://hexo.io/) | Based on Theme: [{theme.name} {theme.version}]({theme.tree})。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。
